### ISSUE TITLE
[BACKEND] Create username and password attempt function

### ISSUE THREAD

**Issue by ren38** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#10]
The username and password need to be taken and compared to what is in the database, then return the relevant changes to the front end.

**Comment by ren38** [comment]
This will only be to accept two strings, a username and a password. For this task, it will not compare these two strings against the database, it will not return any information, and it will not change the view.

**Comment by mwiedera** [comment]
Following guide for securing a web application. Updates to follow.

**Comment by JamesGarrison01** [comment]
Lets work on this after class today. 3/21 - This will set us off on the right course if we work on this together.

**Comment by JamesGarrison01** [comment]
Created - and commited on garrison branch
