### ISSUE TITLE
Install Needed Tools for Database

### ISSUE THREAD

**Issue by JamesGarrison01** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#14]
Spring IDE and MongoDB Atlas and Compass will be needed

**Comment by univeralh** [comment]
Installed Mongodb Compass, and Spring IDE Installed. 

![springmongodbinstalled](https://user-images.githubusercontent.com/15134285/36064337-1c8c0560-0e4f-11e8-8494-ef41b0dd129c.png)
