### ISSUE TITLE
Learn how to database through Mongodb

### ISSUE THREAD

**Issue by JamesGarrison01** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#22]
This will be an extensive learning process. This will be the barebones of the database and is crucial it is learned and executed correctly the first time. 

resource:
https://docs.mongodb.com/manual/core/data-modeling-introduction/

**Comment by univeralh** [comment]
Good Resources found for this: 
Hello World Example - http://www.mkyong.com/mongodb/java-mongodb-hello-world-example/
Example using Spring and Rest - https://github.com/spring-projects/spring-data-examples/blob/master/rest/starbucks/src/main/java/example/springdata/rest/stores/StoreRepository.java
Example of a Board using Mongodb - https://gitgud.io/LynxChan/LynxChan/blob/master/src/be/engine/jsonBuilder.js

**Comment by drlehr** [comment]
Good comments.  Which teammate is univeralh?  :-)

**Comment by univeralh** [comment]
James Garrison. I'll update it.

**Comment by JamesGarrison01** [comment]
Links and documents read and reviewed. Several good resources. Only blocks to starting next task is using Maven. Need to discuss using Maven with team.
