### ISSUE TITLE
Backend UML

### ISSUE THREAD

**Issue by mwiedera** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#31]
Create UML diagram with general specifications for connecting frontend to database.

**Comment by univeralh** [comment]
We need to make sure these go from In-Progress to Done rather than directly from new issues.

**Comment by mwiedera** [comment]
Do we have 2 issues regarding backend uml?

**Comment by univeralh** [comment]
We do. That makes sense. Why it was closed now.

**Comment by JamesGarrison01** [comment]
Removing hours and spring - Appears to be a duplicate task. Still at 50 hours. Discussed with team before removal.
