### ISSUE TITLE
Find Appropriate RST Example Guide

### ISSUE THREAD

**Issue by mwiedera** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#45]
Locate and begin to follow appropriate example guide to setup rst api controller guide to support http requests.

**Comment by mwiedera** [comment]
Thanks to Mike,

http://websystique.com/spring-boot/spring-boot-rest-api-example/

**Comment by JamesGarrison01** [comment]
Should this be in the Sprint 1 Milestones?
