### ISSUE TITLE
Create Basic RST Api Example

### ISSUE THREAD

**Issue by mwiedera** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#46]
More applicable to our situation. Basic example from 

http://websystique.com/spring-boot/spring-boot-rest-api-example/

that we can begin to modify and use in order to better understand Rest API principles and functions.

**Comment by mwiedera** [comment]
Completed example, minor compilation errors to overcome today.

**Comment by JamesGarrison01** [comment]
Should this be in the Sprint 1 Milestones?
