### ISSUE TITLE
Figure out which API's will work best 

### ISSUE THREAD

**Issue by RyanHoward84** [CS3398-Hyderabad-Bluehats/CS3398-Bluehats-S2018#9]
for talking between front end and back end we need to agree upon API's that will pass data back to the database

**Comment by michaelscales88** [comment]
Discussed with Howard. Task may have been mistakenly moved out of the current sprints backlog. Updated based on our conversation.

**Comment by RyanHoward84** [comment]
spring boot, found an example on how to make requests to a spring boot API controller
